default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: 127.0.0.1
  username: root
  password: 123456
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: tabstoday_development

test:
  <<: *default
  database: tabstoday_test

production:
  <<: *default
  database: tabstoday_production
