default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] %>
  username: <%= ENV['DEVELOPMENT_DATABASE_USER_NAME'] %>
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['TEST_DATABASE_HOST'] %>
  username: <%= ENV['TEST_DATABASE_USER_NAME'] %>
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USER_NAME'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
